### ISSUE TITLE
Is the source available anywhere?

### ISSUE THREAD

**Issue by pcn** [sharklinux/llc-bpf#1]

**Comment by sharklinux** [comment]
Hi,

Actually llc-bpf is llc with bpf target enabled, so if you want to build it by yourself, just download llvm source code and configure it by bpf target enabled, then make it, finally rename llc to llc-bpf. :)

There don't have any in house code of llc-bpf.

Thanks.

**Comment by pcn** [comment]
Aha, the llvm llc compiler - got it.
